handle wireguard keys on first boot

diff --git a/customize_image b/customize_image
--- a/customize_image
+++ b/customize_image
@@ -3,40 +3,57 @@
 IMAGE_SOURCE_DIR="source_images"
 IMAGE_DEST_DIR="customized_images"
 OVERWRITE=0
+DISABLE_WIFI=0
+DISABLE_BLUETOOTH=0
+DISABLE_TRIGGERHAPPY=0
+DEBUG=0
 
 # Function to display usage information
 usage() {
-    echo "Usage: $0 -f <image_file> -h <hostname> [-o]"
-    echo "  -f <image_file>  : Path to the source image file."
-    echo "  -h <hostname>    : Hostname for the customized image."
-    echo "  -o               : Overwrite the customized image file if it exists."
+    echo "Usage: $0 -f <image_file> -h <hostname> [--overwrite] [--disable-wifi] [--disable-bluetooth] [--disable-triggerhappy] [--debug]"
+    echo "  -f <image_file>    : Path to the source image file."
+    echo "  -h <hostname>      : Hostname for the customized image."
+    echo "  --overwrite        : Overwrite the customized image file if it exists."
+    echo "  --disable-wifi     : Disable WiFi in the customized image."
+    echo "  --disable-bluetooth: Disable Bluetooth in the customized image."
+    echo "  --disable-triggerhappy: Disable Triggerhappy in the customized image."
+    echo "  --debug            : Run sdm without --batch option."
     exit 1
 }
 
 # Parse command line arguments
-while getopts ":f:h:o" opt; do
-    case ${opt} in
-        f )
-            IMAGE_FILE=$OPTARG
+while [[ "$#" -gt 0 ]]; do
+    case $1 in
+        -f)
+            IMAGE_FILE=$2
+            shift
             ;;
-        h )
-            IMAGE_HOSTNAME=$OPTARG
+        -h)
+            IMAGE_HOSTNAME=$2
+            shift
             ;;
-        o )
+        --overwrite)
             OVERWRITE=1
             ;;
-        \? )
-            echo "Invalid option: $OPTARG" 1>&2
-            usage
+        --disable-wifi)
+            DISABLE_WIFI=1
             ;;
-        : )
-            echo "Invalid option: $OPTARG requires an argument" 1>&2
+        --disable-bluetooth)
+            DISABLE_BLUETOOTH=1
+            ;;
+        --disable-triggerhappy)
+            DISABLE_TRIGGERHAPPY=1
+            ;;
+        --debug)
+            DEBUG=1
+            ;;
+        *)
+            echo "Invalid option: $1" 1>&2
             usage
             ;;
     esac
+    shift
 done
-
-shift $((OPTIND -1))
 
 # Validate input parameters
 if [[ -z "${IMAGE_FILE}" ]] || [[ -z "${IMAGE_HOSTNAME}" ]]; then
@@ -89,15 +106,33 @@ DOCKER_IMAGE_NAME="biosense-sdm"
 
 docker build -t "${DOCKER_IMAGE_NAME}" .
 
-docker run --privileged -it --rm -v "$(pwd)":/home/agent/hostdir -v /dev:/dev "${DOCKER_IMAGE_NAME}" /bin/bash -c "
-sudo sdm \
-    --customize \
+# Construct the disables plugin string
+DISABLES="piwiz"
+if [[ ${DISABLE_WIFI} -eq 1 ]]; then
+    DISABLES="wifi|${DISABLES}"
+fi
+if [[ ${DISABLE_BLUETOOTH} -eq 1 ]]; then
+    DISABLES="bluetooth|${DISABLES}"
+fi
+if [[ ${DISABLE_TRIGGERHAPPY} -eq 1 ]]; then
+    DISABLES="triggerhappy|${DISABLES}"
+fi
+
+# Construct the sdm command
+SDM_COMMAND="sudo sdm --customize"
+if [[ ${DEBUG} -eq 0 ]]; then
+    SDM_COMMAND="${SDM_COMMAND} --batch"
+fi
+SDM_COMMAND="${SDM_COMMAND} \
     --chroot \
+    --plugin disables:\"${DISABLES}\" \
     --plugin @/home/agent/hostdir/sdm-plugin-commands \
     --autologin \
+    --nowait-timesync \
     --regen-ssh-host-keys \
     --hostname ${IMAGE_HOSTNAME} \
-    ${CONTAINER_CUSTOMIZED_IMAGE_FILE}
-"
+    ${CONTAINER_CUSTOMIZED_IMAGE_FILE}"
+
+docker run --privileged -it --rm -v "$(pwd)":/home/agent/hostdir -v /dev:/dev "${DOCKER_IMAGE_NAME}" /bin/bash -c "${SDM_COMMAND}"
 
 exit 0
