misc changes

diff --git a/extras/finalize-biosense-image b/extras/finalize-biosense-image
--- a/extras/finalize-biosense-image
+++ b/extras/finalize-biosense-image
@@ -69,7 +69,7 @@ save_yaml() {
         echo "wifi_password: \"${WIFI_PASSWORD}\""
         echo "latitude: \"${LATITUDE}\""
         echo "longitude: \"${LONGITUDE}\""
-    } > "$yaml_file"
+    } >"$yaml_file"
 }
 
 # Function to find the latest image file in the source directory
@@ -86,7 +86,7 @@ find_latest_image() {
 next_ip() {
     local ip=$1
     local IFS='.'
-    read -r -a ip_parts <<< "$ip"
+    read -r -a ip_parts <<<"$ip"
     if [[ ${ip_parts[3]} -eq 255 ]]; then
         ip_parts[3]=0
         ip_parts[2]=$((ip_parts[2] + 1))
@@ -99,79 +99,79 @@ next_ip() {
 # Parse command line arguments
 while [[ "$#" -gt 0 ]]; do
     case $1 in
-        --wg-ip)
-            WG_IP=$2
-            shift
-            ;;
-        --source-dir)
-            IMAGE_SOURCE_DIR=$2
-            shift
-            ;;
-        --dest-dir)
-            IMAGE_DEST_DIR=$2
-            shift
-            ;;
-        --image-file)
-            IMAGE_FILE=$(basename "$2")
-            shift
-            ;;
-        --config-file)
-            CONFIG_FILE=$2
-            shift
-            ;;
-        --save-config)
-            SAVE_CONFIG_FILE=$2
-            shift
-            ;;
-        --update-config)
-            UPDATE_CONFIG=1
-            ;;
-        --overwrite)
-            OVERWRITE=1
-            ;;
-        --disable-wifi)
-            DISABLE_WIFI=1
-            ;;
-        --disable-bluetooth)
-            DISABLE_BLUETOOTH=1
-            ;;
-        --disable-triggerhappy)
-            DISABLE_TRIGGERHAPPY=1
-            ;;
-        --debug)
-            DEBUG=1
-            ;;
-        --wifi-country)
-            WIFI_COUNTRY=$2
-            shift
-            ;;
-        --wifi-ssid)
-            WIFI_SSID=$2
-            shift
-            ;;
-        --wifi-password)
-            WIFI_PASSWORD=$2
-            shift
-            ;;
-        --latitude)
-            LATITUDE=$2
-            shift
-            ;;
-        --longitude)
-            LONGITUDE=$2
-            shift
-            ;;
-        *)
-            echo "Invalid option: $1" 1>&2
-            usage
-            ;;
+    --wg-ip)
+        WG_IP=$2
+        shift
+        ;;
+    --source-dir)
+        IMAGE_SOURCE_DIR=$2
+        shift
+        ;;
+    --dest-dir)
+        IMAGE_DEST_DIR=$2
+        shift
+        ;;
+    --image-file)
+        IMAGE_FILE=$(basename "$2")
+        shift
+        ;;
+    --config-file)
+        CONFIG_FILE=$2
+        shift
+        ;;
+    --save-config)
+        SAVE_CONFIG_FILE=$2
+        shift
+        ;;
+    --update-config)
+        UPDATE_CONFIG=1
+        ;;
+    --overwrite)
+        OVERWRITE=1
+        ;;
+    --disable-wifi)
+        DISABLE_WIFI=1
+        ;;
+    --disable-bluetooth)
+        DISABLE_BLUETOOTH=1
+        ;;
+    --disable-triggerhappy)
+        DISABLE_TRIGGERHAPPY=1
+        ;;
+    --debug)
+        DEBUG=1
+        ;;
+    --wifi-country)
+        WIFI_COUNTRY=$2
+        shift
+        ;;
+    --wifi-ssid)
+        WIFI_SSID=$2
+        shift
+        ;;
+    --wifi-password)
+        WIFI_PASSWORD=$2
+        shift
+        ;;
+    --latitude)
+        LATITUDE=$2
+        shift
+        ;;
+    --longitude)
+        LONGITUDE=$2
+        shift
+        ;;
+    *)
+        echo "Invalid option: $1" 1>&2
+        usage
+        ;;
     esac
     shift
 done
 
 # If config file is specified, check for yq and the existence of the file only if needed
 if [[ -n "$CONFIG_FILE" ]]; then
-    if ! command -v yq &> /dev/null; then
+    if ! command -v yq &>/dev/null; then
         echo "Error: yq is not installed. Please install yq to use the --config-file option."
         exit 1
     fi
@@ -222,7 +222,7 @@ if [[ -z "${IMAGE_FILE}" ]]; then
 fi
 
 # Generate hostname from WireGuard IP
-IFS='.' read -r -a ip_parts <<< "${WG_IP}"
+IFS='.' read -r -a ip_parts <<<"${WG_IP}"
 HOSTNAME="biosense-${ip_parts[2]}-${ip_parts[3]}"
 
 # Check if the image file exists
@@ -262,7 +262,7 @@ fi
 DOCKER_IMAGE_NAME="biosense-sdm"
 docker build -t "${DOCKER_IMAGE_NAME}" .
 
-SDM_COMMAND="sudo sdm --customize --extend --xmb 2048"
+SDM_COMMAND="sudo sdm --burn --burnfile /home/agent/hostdir/${CUSTOMIZED_IMAGE_FILE}"
 if [[ ${DEBUG} -eq 0 ]]; then
     SDM_COMMAND="${SDM_COMMAND} --batch"
 fi
@@ -282,8 +282,7 @@ fi
 SDM_COMMAND="${SDM_COMMAND} \
     --chroot \
     --plugin disables:\"${DISABLES}\" \
-    --plugin /home/agent/hostdir/sdm-biosense-finalize-image:\"wg_ip=${WG_IP}|latitude=${LATITUDE}|longitude=${LONGITUDE}\" \
-    /home/agent/hostdir/${CUSTOMIZED_IMAGE_FILE}"
+    --plugin /home/agent/hostdir/finalize-biosense-image-plugin:\"wg_ip=${WG_IP}|latitude=${LATITUDE}|longitude=${LONGITUDE}\""
 
 # Add network plugin if WiFi details are specified
 NETWORK_PLUGIN_ARGS=""
@@ -291,7 +290,7 @@ NETWORK_PLUGIN_ARGS=""
 [ -n "${WIFI_PASSWORD}" ] && NETWORK_PLUGIN_ARGS="${NETWORK_PLUGIN_ARGS}wifipassword=${WIFI_PASSWORD}|"
 [ -n "${WIFI_COUNTRY}" ] && NETWORK_PLUGIN_ARGS="${NETWORK_PLUGIN_ARGS}wificountry=${WIFI_COUNTRY}|"
 if [[ -n "${NETWORK_PLUGIN_ARGS}" ]]; then
-    NETWORK_PLUGIN_ARGS="${NETWORK_PLUGIN_ARGS%|}"  # Remove trailing '|'
+    NETWORK_PLUGIN_ARGS="${NETWORK_PLUGIN_ARGS%|}" # Remove trailing '|'
     SDM_COMMAND="${SDM_COMMAND} --plugin network:\"${NETWORK_PLUGIN_ARGS}|noipv6\""
 fi
 
@@ -299,7 +298,7 @@ docker run --privileged -it --rm -v "$(pwd)":/home/agent/hostdir -v /dev:/dev "$
 
 # Save the current configuration to a file if requested
 if [[ -n "${SAVE_CONFIG_FILE}" ]]; then
-    if ! command -v yq &> /dev/null; then
+    if ! command -v yq &>/dev/null; then
         echo "Error: yq is not installed. Please install yq to use the --save-config option."
         exit 1
     fi
@@ -310,7 +309,7 @@ fi
 
 # Update the specified configuration file if requested
 if [[ ${UPDATE_CONFIG} -eq 1 && -n "${CONFIG_FILE}" ]]; then
-    if ! command -v yq &> /dev/null; then
+    if ! command -v yq &>/dev/null; then
         echo "Error: yq is not installed. Please install yq to use the --update-config option."
         exit 1
     fi
diff --git a/extras/init-biosense-image b/extras/init-biosense-image
--- a/extras/init-biosense-image
+++ b/extras/init-biosense-image
@@ -19,28 +19,28 @@ usage() {
 # Parse command line arguments
 while [[ "$#" -gt 0 ]]; do
     case $1 in
-        --source-dir)
-            IMAGE_SOURCE_DIR=$2
-            shift
-            ;;
-        --dest-dir)
-            IMAGE_DEST_DIR=$2
-            shift
-            ;;
-        --image-file)
-            IMAGE_FILE=$(basename "$2")
-            shift
-            ;;
-        --overwrite)
-            OVERWRITE=1
-            ;;
-        --debug)
-            DEBUG=1
-            ;;
-        *)
-            echo "Invalid option: $1" 1>&2
-            usage
-            ;;
+    --source-dir)
+        IMAGE_SOURCE_DIR=$2
+        shift
+        ;;
+    --dest-dir)
+        IMAGE_DEST_DIR=$2
+        shift
+        ;;
+    --image-file)
+        IMAGE_FILE=$(basename "$2")
+        shift
+        ;;
+    --overwrite)
+        OVERWRITE=1
+        ;;
+    --debug)
+        DEBUG=1
+        ;;
+    *)
+        echo "Invalid option: $1" 1>&2
+        usage
+        ;;
     esac
     shift
 done
@@ -80,7 +80,7 @@ fi
 SDM_COMMAND="${SDM_COMMAND} \
     --chroot \
     --plugin @/home/agent/hostdir/sdm-plugin-commands \
-    --plugin /home/agent/hostdir/sdm-biosense-init-image \
+    --plugin /home/agent/hostdir/init-biosense-image-plugin \
     /home/agent/hostdir/${CUSTOMIZED_IMAGE_FILE}"
 
 docker run --privileged -it --rm -v "$(pwd)":/home/agent/hostdir -v /dev:/dev "${DOCKER_IMAGE_NAME}" /bin/bash -c "${SDM_COMMAND}"
